AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  makecommandandrunbatch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 900
      Role: 'arn:aws:iam::hogehoge:role/make_command_and_run_batch_role'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
        Schedule2:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *)
        Schedule3:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)
